# Generated by Django 3.2.20 on 2023-07-31 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cropped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cropped_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField(null=True)),
                ('date_release', models.DateField(null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('prod_id', models.CharField(max_length=128, null=True)),
                ('original_price_currency', models.CharField(max_length=64, null=True)),
                ('original_price_with_currency', models.CharField(max_length=64, null=True)),
                ('krw', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('img_path', models.TextField()),
                ('image', models.ImageField(upload_to='./')),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.IntegerField(null=True)),
                ('cropped_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_detect.cropped')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_detect.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=255)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_detect.product')),
            ],
        ),
        migrations.AddField(
            model_name='cropped',
            name='uploaded_img_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_detect.uploadedimg'),
        ),
    ]
