# Generated by Django 3.2.20 on 2023-08-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_detect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimg',
            name='img_path',
        ),
    ]
